@RJA3_HostAddress = http://localhost:5211

GET {{RJA3_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{RJA3_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "TestPassword123!",
  "firstName": "Test",
  "lastName": "User"
}

###
