// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RJA3.Modules.FoundItems.Persistence;

#nullable disable

namespace RJA3.Modules.FoundItems.Migrations
{
    [DbContext(typeof(FoundItemDbContext))]
    partial class FoundItemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RJA3.Modules.FoundItems.Domain.FoundItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("FinderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FoundAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FoundItems");

                    b.HasDiscriminator<int>("ItemType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RJA3.Modules.FoundItems.Domain.PhoneFoundItem", b =>
                {
                    b.HasBaseType("RJA3.Modules.FoundItems.Domain.FoundItem");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("RJA3.Modules.FoundItems.Domain.FoundItem", b =>
                {
                    b.OwnsMany("RJA3.Modules.FoundItems.Domain.SecurityQuestion", "SecurityQuestions", b1 =>
                        {
                            b1.Property<string>("FoundItemId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ExpectedAnswer")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Question")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.HasKey("FoundItemId", "Id");

                            b1.ToTable("SecurityQuestion");

                            b1.WithOwner()
                                .HasForeignKey("FoundItemId");
                        });

                    b.Navigation("SecurityQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
